# Generated by Django 4.0.4 on 2022-05-15 16:19

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('pub_date', models.DateTimeField(null=True)),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('rating', models.FloatField()),
                ('reviews_count', models.IntegerField()),
                ('wma_count', models.IntegerField()),
                ('photo_url', models.URLField(null=True)),
                ('ingredient_groups', models.JSONField()),
                ('authors', models.ManyToManyField(related_name='recipes', to='recipes.author')),
                ('tags', models.ManyToManyField(related_name='recipes', to='recipes.tag')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('pub_date'), descending=True, nulls_last=True)],
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['pub_date'], name='recipes_rec_pub_dat_caa7fa_idx'),
        ),
    ]
