# Generated by Django 4.0.4 on 2022-05-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
