# Generated by Django 4.0.4 on 2022-05-20 09:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.expressions
from django.db import migrations


def fill_main_tsvector_field(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    ts_vector = django.contrib.postgres.search.SearchVector(
        'url', 'name', 'title', 'description', 'short_description', 'ingredient_groups',
        config='english',
    )
    Recipe.objects.all().update(main_tsvector=ts_vector)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_photo_url_alter_recipe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='main_tsvector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.RunPython(fill_main_tsvector_field),
        migrations.AlterField(
            model_name='recipe',
            name='main_tsvector',
            field=django.contrib.postgres.search.SearchVectorField(),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('main_tsvector'), name='main_tsvector_idx'),
        ),
    ]
