# Generated by Django 4.0.4 on 2022-05-21 15:26

import django.contrib.postgres.indexes
import django.db.models.expressions
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_main_tsvector_recipe_main_tsvector_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipe',
            name='main_tsvector_idx',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='main_tsvector',
            new_name='full_text_tsvector',
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('full_text_tsvector'), name='full_text_tsvector_idx'),
        ),
    ]
