# Generated by Django 4.0.4 on 2022-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_full_text_tsvector_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(),
        ),
    ]
