# Generated by Django 4.0.4 on 2022-05-24 16:54

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_author_name_alter_tag_name'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='author',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='author_name_gin_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='tag_name_gin_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
