# Generated by Django 4.0.4 on 2022-05-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_author_author_name_gin_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.TextField(choices=[('Bon Appétit', 'Bon Appetit')], default='Bon Appétit'),
            preserve_default=False,
        ),
    ]
