# Generated by Django 4.0.4 on 2022-05-28 09:25

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_source'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipes_rec_pub_dat_caa7fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipes_rec_full_te_1f199b_gin',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipes_rec_essenti_999a14_gin',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='essentials_tsvector',
            new_name='_essentials_tsvector',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='full_text_tsvector',
            new_name='_full_text_tsvector',
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['pub_date'], name='recipe_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_full_text_tsvector'], name='recipe_full_text_tsv_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_essentials_tsvector'], name='recipe_essentials_tsv_idx'),
        ),
    ]
