# Generated by Django 4.0.5 on 2022-07-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe__ingredients_tsvector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='raw_json',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
