# Generated by Django 4.0.5 on 2022-07-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipe_raw_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='raw_json',
            field=models.JSONField(null=True),
        ),
    ]
