# Generated by Django 4.0.4 on 2022-05-18 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_photo_url_alter_recipe_url'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='recipes.author'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='telegram.chat'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='recipes.tag'),
        ),
    ]
