# Generated by Django 4.0.4 on 2022-05-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_photo_url_alter_recipe_url'),
        ('telegram', '0002_alter_subscription_author_alter_subscription_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_recipe_date', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='telegram.chat')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='recipes.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddConstraint(
            model_name='tagsubscription',
            constraint=models.UniqueConstraint(fields=('chat', 'tag'), name='unique_tag_subscription'),
        ),
    ]
