# Generated by Django 4.0.4 on 2022-05-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_alter_tagsubscription_chat_alter_tagsubscription_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('query', models.TextField()),
                ('page_n', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_messages', to='telegram.chat')),
            ],
        ),
    ]
