# Generated by Django 4.0.4 on 2022-05-22 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_essentials_tsvector_and_more'),
        ('telegram', '0005_searchrequestmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='liked_recipes',
            field=models.ManyToManyField(to='recipes.recipe'),
        ),
        migrations.CreateModel(
            name='LikedListMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('page_n', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_list_messages', to='telegram.chat')),
            ],
        ),
    ]
