# Generated by Django 4.0.4 on 2022-05-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_searchlistmessage_delete_searchrequestmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='first_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
