# Generated by Django 4.0.4 on 2022-05-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_alter_chat_first_name_alter_chat_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchlistmessage',
            old_name='query',
            new_name='recipe_query',
        ),
        migrations.AddField(
            model_name='searchlistmessage',
            name='ingredients_query',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
