# Generated by Django 4.0.4 on 2022-05-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe__ingredients_tsvector_and_more'),
        ('telegram', '0009_rename_query_searchlistmessage_recipe_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='blocked_authors',
            field=models.ManyToManyField(to='recipes.author'),
        ),
        migrations.AddField(
            model_name='chat',
            name='blocked_tags',
            field=models.ManyToManyField(to='recipes.tag'),
        ),
    ]
