# Generated by Django 4.0.5 on 2022-06-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_chat_blocked_authors_chat_blocked_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedlistmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.chat'),
        ),
        migrations.AlterField(
            model_name='searchlistmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.chat'),
        ),
    ]
