# Generated by Django 4.0.5 on 2022-06-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_alter_likedlistmessage_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
